### ISSUE TITLE
Request GitHub KYC-smartwzt

### ISSUE THREAD

**Issue by hellowzt** [DigitalPlatDev/FreeDomain#26811]
### KYC Using Your GitHub Account

Please make sure your GitHub account meets the following requirements (all are required):

- [ ] The issue title must be: Request GitHub KYC - Your US.KG Panel registered username. This ensures our automated script can detect your registered username. (For example, your title should be:  **Request GitHub KYC-example**)
- [ ] This is not a new GitHub account; it has existing repositories and stars.
- [ ] This is my first US.KG NIC Panel account.
- [ ] I promise not to use the domain name for criminal or abusive purposes. 
- [ ] Please star this repository, This will let more people know about this project!

**Your Account Details (US.KG NIC Panel):**

Please fill out the following information; otherwise, your request will not be processed:

- Username: smartwzt
- Reason for Registering the .US.KG Domain Name (Why):Study and build a website.

**Comment by laorui** [comment]
请求再次发送一封注册成功后的邮件，确认注册成功的邮件。谢谢

________________________________
发件人: hellowzt ***@***.***>
发送时间: 2024年11月22日 上午 10:15
收件人: DigitalPlatDev/FreeDomain ***@***.***>
抄送: Subscribed ***@***.***>
主题: [DigitalPlatDev/FreeDomain] Request GitHub KYC-smartwzt (Issue #26811)


KYC Using Your GitHub Account

Please make sure your GitHub account meets the following requirements (all are required):

  *    The issue title must be: Request GitHub KYC - Your US.KG Panel registered username. This ensures our automated script can detect your registered username. (For example, your title should be: Request GitHub KYC-example)
  *    This is not a new GitHub account; it has existing repositories and stars.
  *    This is my first US.KG NIC Panel account.
  *    I promise not to use the domain name for criminal or abusive purposes.
  *    Please star this repository, This will let more people know about this project!

Your Account Details (US.KG NIC Panel):

Please fill out the following information; otherwise, your request will not be processed:

  *   Username: smartwzt
  *   Reason for Registering the .US.KG Domain Name (Why):Study and build a website.

―

**Comment by laorui** [comment]
@劳 ***@***.***>
注册us域名的原因：用于自己学习和研究之用。
绝不会用于犯罪活动。

________________________________
发件人: hellowzt ***@***.***>
发送时间: 2024年11月22日 上午 10:15
收件人: DigitalPlatDev/FreeDomain ***@***.***>
抄送: Subscribed ***@***.***>
主题: [DigitalPlatDev/FreeDomain] Request GitHub KYC-smartwzt (Issue #26811)


KYC Using Your GitHub Account

Please make sure your GitHub account meets the following requirements (all are required):

  *    The issue title must be: Request GitHub KYC - Your US.KG Panel registered username. This ensures our automated script can detect your registered username. (For example, your title should be: Request GitHub KYC-example)
  *    This is not a new GitHub account; it has existing repositories and stars.
  *    This is my first US.KG NIC Panel account.
  *    I promise not to use the domain name for criminal or abusive purposes.
  *    Please star this repository, This will let more people know about this project!

Your Account Details (US.KG NIC Panel):

Please fill out the following information; otherwise, your request will not be processed:

  *   Username: smartwzt
  *   Reason for Registering the .US.KG Domain Name (Why):Study and build a website.

―

**Comment by laorui** [comment]
请求Github  kyc-
***@***.***
存储库;xiaoloufengyue
这是我的第一个美国，KG网卡面板账号，本人承诺不将该域名用于犯罪或滥用的目的
用户名：laorui788
注册原因：主要用于学习和研究，别无它用。

________________________________
发件人: hellowzt ***@***.***>
发送时间: 2024年11月22日 上午 10:15
收件人: DigitalPlatDev/FreeDomain ***@***.***>
抄送: Subscribed ***@***.***>
主题: [DigitalPlatDev/FreeDomain] Request GitHub KYC-smartwzt (Issue #26811)


KYC Using Your GitHub Account

Please make sure your GitHub account meets the following requirements (all are required):

  *    The issue title must be: Request GitHub KYC - Your US.KG Panel registered username. This ensures our automated script can detect your registered username. (For example, your title should be: Request GitHub KYC-example)
  *    This is not a new GitHub account; it has existing repositories and stars.
  *    This is my first US.KG NIC Panel account.
  *    I promise not to use the domain name for criminal or abusive purposes.
  *    Please star this repository, This will let more people know about this project!

Your Account Details (US.KG NIC Panel):

Please fill out the following information; otherwise, your request will not be processed:

  *   Username: smartwzt
  *   Reason for Registering the .US.KG Domain Name (Why):Study and build a website.

―
